### ISSUE TITLE
Nuget, couldn't find the new attributes

### ISSUE THREAD

**Issue by cgasis** [benmccallum/CoreMvc#1]
Nevermind Ben, i got it! :)

Hi Ben,

I tried pulling this via nuget package, but i don't find the 'IpAddressAuthorize' attribute. Am i missing some steps here? Thanks in advance!

Current Project:
MVC5, VS2013

**Comment by benmccallum** [comment]
Awesome. I only quickly chucked those in there from another project so I haven't tested them. Let me know if you have any issues.
